import { ClothingBoutique } from './types';

export const INITIAL_BOUTIQUES: ClothingBoutique[] = [
  {
    id: 'boutique-1',
    name: 'Al-Haram Trendz & Boutique',
    nameHi: 'अल-हरम ट्रेंड्स एंड बुटीक',
    rating: 4.9,
    deliveryTime: '2-3 Days (Stitching Available)',
    deliveryTimeHi: '2-3 दिन (सिलाई उपलब्ध)',
    minOrder: 499,
    area: 'Maudaha',
    address: 'Near Jama Masjid Chauraha, Maudaha',
    addressHi: 'जामा मस्जिद चौराहा के पास, मौदहा',
    specialty: 'Ethnic & Wedding wear, Designer Sherwanis & Bridal Lehengas',
    specialtyHi: 'पारंपरिक और शादी के परिधान, डिजाइनर शेरवानी और दुल्हन के लहंगे',
    banner: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?q=80&w=600&auto=format&fit=crop',
    items: [
      {
        id: 'cloth-1-1',
        name: 'Royal Zardozi Velvet Lehenga Set',
        nameHi: 'रॉयल जरदोजी वेलवेट लहंगा सेट',
        price: 4999,
        category: 'ethnic',
        image: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?q=80&w=250&auto=format&fit=crop',
        description: 'Heavy designer velvet lehenga with premium zardozi embroidery and netted matching dupatta.',
        descriptionHi: 'प्रीमियम जरदोजी कढ़ाई और नेट के मैचिंग दुपट्टे के साथ भारी डिजाइनर मखमली लहंगा।',
        sizes: ['M', 'L', 'XL', 'Free Size'],
        hasStitchingOption: true, replacementPolicy: '7 Days Replacement', replacementPolicyHi: '7 दिन की रिप्लेसमेंट'
      },
      {
        id: 'cloth-1-2',
        name: 'Classic Banarasi Silk Sherwani',
        nameHi: 'क्लासिक बनारसी सिल्क शेरवानी',
        price: 3499,
        category: 'ethnic',
        image: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?q=80&w=250&auto=format&fit=crop',
        description: 'Elegant cream Banarasi silk sherwani with golden motifs, ideal for grooms & festivals.',
        descriptionHi: 'सुनहरे रूपांकनों के साथ सुरुचिपूर्ण क्रीम बनारसी सिल्क शेरवानी, दूल्हे और त्योहारों के लिए आदर्श।',
        sizes: ['M', 'L', 'XL', 'XXL'],
        hasStitchingOption: true, replacementPolicy: '7 Days Replacement', replacementPolicyHi: '7 दिन की रिप्लेसमेंट'
      },
      {
        id: 'cloth-1-3',
        name: 'Georgette Anarkali Suit with Dupatta',
        nameHi: 'जॉर्जेट अनारकली सूट दुपट्टे के साथ',
        price: 1899,
        category: 'ethnic',
        image: 'https://images.unsplash.com/photo-1608748010899-18f300247112?q=80&w=250&auto=format&fit=crop',
        description: 'Floral printed georgette Anarkali with intricate sequin border work and soft lining.',
        descriptionHi: 'जटिल सेक्विन बॉर्डर वर्क और सॉफ्ट इनर लाइनिंग के साथ फ्लोरल प्रिंटेड जॉर्जेट अनारकली सूट।',
        sizes: ['S', 'M', 'L', 'XL'],
        hasStitchingOption: true, replacementPolicy: '7 Days Replacement', replacementPolicyHi: '7 दिन की रिप्लेसमेंट'
      },
      {
        id: 'cloth-1-4',
        name: 'Golden Thread Embroidered Jutis',
        nameHi: 'गोल्डन थ्रेड कढ़ाई वाली जूती',
        price: 599,
        category: 'footwear',
        image: 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?q=80&w=250&auto=format&fit=crop',
        description: 'Traditional handcrafted Punjabi jutis with elegant golden thread embroidery.',
        descriptionHi: 'शानदार सोने के धागे की कढ़ाई के साथ पारंपरिक हस्तनिर्मित पंजाबी जूती।',
        sizes: ['7', '8', '9', '10'],
        hasStitchingOption: false, replacementPolicy: '7 Days Replacement', replacementPolicyHi: '7 दिन की रिप्लेसमेंट'
      }
    ]
  },
  {
    id: 'boutique-2',
    name: 'Sita Ram Saree Sangam',
    nameHi: 'सीता राम साड़ी संगम',
    rating: 4.8,
    deliveryTime: 'Same-Day Delivery (Pre-stitched blouse +1 day)',
    deliveryTimeHi: 'उसी दिन डिलीवरी (सिली हुई ब्लाउज में +1 दिन)',
    minOrder: 399,
    area: 'Maudaha',
    address: 'Gandhi Ganj Bazar, Maudaha',
    addressHi: 'गांधी गंज बाजार, मौदहा',
    specialty: 'Pure Banarasi Sarees, Chanderi Silk, Georgette & Wedding Drapes',
    specialtyHi: 'प्योर बनारसी साड़ियां, चंदेरी सिल्क, जॉर्जेट और शादी के परिधान',
    banner: 'https://images.unsplash.com/photo-1610030469668-93535c17b6b3?q=80&w=600&auto=format&fit=crop',
    items: [
      {
        id: 'cloth-2-1',
        name: 'Royal Red Kanjivaram Silk Saree',
        nameHi: 'रॉयल रेड कांजीवरम सिल्क साड़ी',
        price: 2499,
        category: 'ethnic',
        image: 'https://images.unsplash.com/photo-1610030469668-93535c17b6b3?q=80&w=250&auto=format&fit=crop',
        description: 'Traditional heavy gold zari bordered pure Kanjivaram style saree with unstitched blouse.',
        descriptionHi: 'पारंपरिक हैवी गोल्ड जरी बॉर्डर वाली प्योर कांजीवरम स्टाइल साड़ी, बिना सिले ब्लाउज के साथ।',
        sizes: ['Free Size'],
        hasStitchingOption: true, replacementPolicy: '7 Days Replacement', replacementPolicyHi: '7 दिन की रिप्लेसमेंट'
      },
      {
        id: 'cloth-2-2',
        name: 'Elegant Mustard Chanderi Silk Saree',
        nameHi: 'एलिगेंट मस्टर्ड चंदेरी सिल्क साड़ी',
        price: 1599,
        category: 'ethnic',
        image: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?q=80&w=250&auto=format&fit=crop',
        description: 'Lightweight Chanderi silk with silver border, ideal for Pujas and office wear.',
        descriptionHi: 'चांदी के बॉर्डर के साथ हल्के वजन की चंदेरी सिल्क साड़ी, पूजा और कार्यालय के लिए आदर्श।',
        sizes: ['Free Size'],
        hasStitchingOption: true, replacementPolicy: '7 Days Replacement', replacementPolicyHi: '7 दिन की रिप्लेसमेंट'
      },
      {
        id: 'cloth-2-3',
        name: 'Pearl Embroidered Kundan Set',
        nameHi: 'पर्ल एम्ब्रॉयडर्ड कुंदन सेट',
        price: 899,
        category: 'accessories',
        image: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?q=80&w=250&auto=format&fit=crop',
        description: 'Glistening choker necklace set with matched hanging jhumkas, crafted in premium Kundan look.',
        descriptionHi: 'शानदार चोकर नेकलेस सेट के साथ मेल खाते लटकने वाले झुमके, प्रीमियम कुंदन लुक में निर्मित।',
        sizes: ['Adjustable'],
        hasStitchingOption: false, replacementPolicy: '7 Days Replacement', replacementPolicyHi: '7 दिन की रिप्लेसमेंट'
      }
    ]
  },
  {
    id: 'boutique-3',
    name: 'Maudaha Fashion Hub',
    nameHi: 'मौदहा फैशन हब',
    rating: 4.7,
    deliveryTime: 'Same-Day Delivery',
    deliveryTimeHi: 'उसी दिन डिलीवरी',
    minOrder: 299,
    area: 'Maudaha',
    address: 'Near Station Road, Opposite HDFC Bank, Maudaha',
    addressHi: 'स्टेशन रोड के पास, एचडीएफसी बैंक के सामने, मौदहा',
    specialty: 'Trendy Western Casuals, Stylish Jeans, Shirts & Jackets',
    specialtyHi: 'ट्रेंडी वेस्टर्न कैजुअल, स्टाइलिश जींस, शर्ट और जैकेट',
    banner: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?q=80&w=600&auto=format&fit=crop',
    items: [
      {
        id: 'cloth-3-1',
        name: 'Premium Slim Fit Indigo Jeans',
        nameHi: 'प्रीमियम स्लिम फिट इंडिगो जींस',
        price: 1199,
        category: 'western',
        image: 'https://images.unsplash.com/photo-1542272604-787c3835535d?q=80&w=250&auto=format&fit=crop',
        description: 'Highly stretchable and breathable denim, crafted for everyday extreme comfort.',
        descriptionHi: 'दैनिक अत्यधिक आराम के लिए तैयार की गई, अत्यधिक खिंचावदार और सांस लेने योग्य डेनिम जींस।',
        sizes: ['30', '32', '34', '36'],
        hasStitchingOption: false, replacementPolicy: '7 Days Replacement', replacementPolicyHi: '7 दिन की रिप्लेसमेंट'
      },
      {
        id: 'cloth-3-2',
        name: 'Floral Print Summer Resort Shirt',
        nameHi: 'फ्लोरल प्रिंट समर रिसॉर्ट शर्ट',
        price: 699,
        category: 'western',
        image: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?q=80&w=250&auto=format&fit=crop',
        description: 'Lightweight cuban-collar floral summer shirt, premium rayon blend.',
        descriptionHi: 'हल्के वजन की क्यूबन-कॉलर फ्लोरल समर शर्ट, प्रीमियम रेयॉन ब्लेंड कपड़ा।',
        sizes: ['S', 'M', 'L', 'XL'],
        hasStitchingOption: false, replacementPolicy: '7 Days Replacement', replacementPolicyHi: '7 दिन की रिप्लेसमेंट'
      },
      {
        id: 'cloth-3-3',
        name: 'Womens Crop Denim Jacket',
        nameHi: 'महिला क्रॉप डेनिम जैकेट',
        price: 1499,
        category: 'western',
        image: 'https://images.unsplash.com/photo-1576995853123-5a10305d93c0?q=80&w=250&auto=format&fit=crop',
        description: 'Chic faded blue cropped denim jacket with silver metal buttons and double chest pockets.',
        descriptionHi: 'सिल्वर मेटल बटन और डबल चेस्ट पॉकेट के साथ आकर्षक फेडेड ब्लू क्रॉप्ड डेनिम जैकेट।',
        sizes: ['S', 'M', 'L'],
        hasStitchingOption: false, replacementPolicy: '7 Days Replacement', replacementPolicyHi: '7 दिन की रिप्लेसमेंट'
      },
      {
        id: 'cloth-3-4',
        name: 'Minimalist Leather White Sneakers',
        nameHi: 'मिनिमलिस्ट लेदर व्हाइट स्नीकर्स',
        price: 1299,
        category: 'footwear',
        image: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?q=80&w=250&auto=format&fit=crop',
        description: 'Ultra-cushioned clean white sneakers, pairs beautifully with denim and casual wear.',
        descriptionHi: 'अल्ट्रा-कुशन वाले साफ सफेद स्नीकर्स, डेनिम और कैजुअल वियर के साथ खूबसूरती से मेल खाते हैं।',
        sizes: ['7', '8', '9', '10'],
        hasStitchingOption: false, replacementPolicy: '7 Days Replacement', replacementPolicyHi: '7 दिन की रिप्लेसमेंट'
      }
    ]
  },
  {
    id: 'boutique-4',
    name: 'Bal Gopal & Pari Kids Wear',
    nameHi: 'बाल गोपाल और परी किड्स वियर',
    rating: 4.6,
    deliveryTime: 'Same-Day Delivery',
    deliveryTimeHi: 'उसी दिन डिलीवरी',
    minOrder: 199,
    area: 'Maudaha',
    address: 'Hospital Road, Maudaha',
    addressHi: 'अस्पताल रोड, मौदहा',
    specialty: 'Adorable Festive Wear for Boys & Girls, Soft Cotton Basics',
    specialtyHi: 'लड़कों और लड़कियों के लिए प्यारे उत्सव परिधान, सॉफ्ट कॉटन बेसिक्स',
    banner: 'https://images.unsplash.com/photo-1503919545889-aef636e10ad4?q=80&w=600&auto=format&fit=crop',
    items: [
      {
        id: 'cloth-4-1',
        name: 'Boys Cotton Silk Kurta Pajama Set',
        nameHi: 'बॉयज कॉटन सिल्क कुर्ता पायजामा सेट',
        price: 799,
        category: 'kids',
        image: 'https://images.unsplash.com/photo-1503919545889-aef636e10ad4?q=80&w=250&auto=format&fit=crop',
        description: 'Breathable and soft cotton silk ethnic set, completely itch-free for delicate kids skin.',
        descriptionHi: 'सांस लेने योग्य और नरम सूती रेशम पारंपरिक सेट, बच्चों की नाजुक त्वचा के लिए पूरी तरह से खुजली-मुक्त।',
        sizes: ['2-3Y', '4-5Y', '6-7Y', '8-9Y'],
        hasStitchingOption: false, replacementPolicy: '7 Days Replacement', replacementPolicyHi: '7 दिन की रिप्लेसमेंट'
      },
      {
        id: 'cloth-4-2',
        name: 'Girls Netted Princess Fairy Frock',
        nameHi: 'गर्ल्स नेटेड प्रिंसेस फेयरी फ्रॉक',
        price: 999,
        category: 'kids',
        image: 'https://images.unsplash.com/photo-1621452773781-0f992fd1f5cb?q=80&w=250&auto=format&fit=crop',
        description: 'Beautiful multi-layered mesh fairy frock with shiny bow, perfect for birthdays and parties.',
        descriptionHi: 'चमकदार धनुष के साथ सुंदर बहु-स्तरीय जालीदार परी फ्रॉक, जन्मदिन और पार्टियों के लिए एकदम सही।',
        sizes: ['3-4Y', '5-6Y', '7-8Y', '9-10Y'],
        hasStitchingOption: false, replacementPolicy: '7 Days Replacement', replacementPolicyHi: '7 दिन की रिप्लेसमेंट'
      }
    ]
  },
  {
    id: 'boutique-5',
    name: 'Maudaha Gold & Silver Palace',
    nameHi: 'मौदहा गोल्ड एंड सिल्वर पैलेस',
    rating: 4.9,
    deliveryTime: 'Same-Day Insured Delivery',
    deliveryTimeHi: 'उसी दिन बीमित डिलीवरी',
    minOrder: 499,
    area: 'Maudaha',
    address: 'Saraf Bazar, Maudaha',
    addressHi: 'सराफ बाजार, मौदहा',
    specialty: 'Exquisite 22k Gold Ornaments, Kundan Chokers, Diamond Rings & Silver Anklets',
    specialtyHi: 'उत्कृष्ट 22k सोने के आभूषण, कुंदन चोकर, हीरे की अंगूठियां और चांदी की पायल',
    banner: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?q=80&w=600&auto=format&fit=crop',
    shopType: 'jewellery',
    items: [
      {
        id: 'jewel-1-1',
        name: 'Royal Gold Plated Bridal Choker Set',
        nameHi: 'रॉयल गोल्ड प्लेटेड ब्राइडल चोकर सेट',
        price: 3499,
        category: 'accessories',
        image: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?q=80&w=250&auto=format&fit=crop',
        description: 'Premium gold plated choker with intricate design, matching long earrings and maang tikka.',
        descriptionHi: 'जटिल डिजाइन के साथ प्रीमियम गोल्ड प्लेटेड चोकर, मैचिंग लंबे झुमके और मांग टीका।',
        sizes: ['Adjustable'],
        hasStitchingOption: false,
        replacementPolicy: '7 Days Replacement',
        replacementPolicyHi: '7 दिन की रिप्लेसमेंट'
      },
      {
        id: 'jewel-1-2',
        name: 'Handcrafted Kundan Jhumka Earrings',
        nameHi: 'हस्तनिर्मित कुंदन झुमका झुमके',
        price: 850,
        category: 'accessories',
        image: 'https://images.unsplash.com/photo-1630019852942-f89202989a59?q=80&w=250&auto=format&fit=crop',
        description: 'Exquisite traditional Kundan hangings with pearl drops, lightweight and beautiful.',
        descriptionHi: 'मोती की बूंदों के साथ उत्तम पारंपरिक कुंदन लटकन, हल्के वजन और सुंदर।',
        sizes: ['Standard'],
        hasStitchingOption: false,
        replacementPolicy: '7 Days Replacement',
        replacementPolicyHi: '7 दिन की रिप्लेसमेंट'
      },
      {
        id: 'jewel-1-3',
        name: 'Pure Silver Designer Payal (Anklets)',
        nameHi: 'प्योर सिल्वर डिजाइनर पायल',
        price: 1200,
        category: 'accessories',
        image: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?q=80&w=250&auto=format&fit=crop',
        description: 'Pair of highly durable pure silver anklets with soft ringing ghungroos.',
        descriptionHi: 'सॉफ्ट बजने वाले घुंघरू के साथ अत्यधिक टिकाऊ शुद्ध चांदी की पायल की जोड़ी।',
        sizes: ['Standard'],
        hasStitchingOption: false,
        replacementPolicy: '7 Days Replacement',
        replacementPolicyHi: '7 दिन की रिप्लेसमेंट'
      }
    ]
  },
  {
    id: 'boutique-6',
    name: 'Anupam Jewellers & Gems',
    nameHi: 'अनुपम ज्वेलर्स एंड जेम्स',
    rating: 4.8,
    deliveryTime: 'Same-Day Delivery',
    deliveryTimeHi: 'उसी दिन डिलीवरी',
    minOrder: 299,
    area: 'Maudaha',
    address: 'Near Gandhi Chauraha, Maudaha',
    addressHi: 'गांधी चौराहा के पास, मौदहा',
    specialty: 'Fashion Jewellery, Royal Rajputi Poshak Jewellery, Pearls & Antique Chokers',
    specialtyHi: 'फैशन ज्वेलरी, रॉयल राजपूती पोशाक आभूषण, मोती और प्राचीन चोकर',
    banner: 'https://images.unsplash.com/photo-1601121141461-9d6647bca1ed?q=80&w=600&auto=format&fit=crop',
    shopType: 'jewellery',
    items: [
      {
        id: 'jewel-2-1',
        name: 'Royal Pearl Bead Multi-Layer Necklace Set',
        nameHi: 'शाही मोती मनका बहु-परत हार सेट',
        price: 1499,
        category: 'accessories',
        image: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?q=80&w=250&auto=format&fit=crop',
        description: 'Elegant multi-layered premium glass pearl necklace set with dangling earrings.',
        descriptionHi: 'लटकते झुमके के साथ सुरुचिपूर्ण बहु-स्तरीय प्रीमियम ग्लास मोती का हार सेट।',
        sizes: ['Adjustable'],
        hasStitchingOption: false,
        replacementPolicy: '7 Days Replacement',
        replacementPolicyHi: '7 दिन की रिप्लेसमेंट'
      },
      {
        id: 'jewel-2-2',
        name: 'Gold Plated Traditional Kada Bangles',
        nameHi: 'गोल्ड प्लेटेड पारंपरिक कड़ा चूड़ियाँ',
        price: 650,
        category: 'accessories',
        image: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?q=80&w=250&auto=format&fit=crop',
        description: 'Set of 2 beautifully engraved gold-plated copper kadas with screw closure.',
        descriptionHi: 'स्क्रू क्लोजर के साथ 2 खूबसूरती से नक्काशीदार गोल्ड-प्लेटेड तांबे के कड़ों का सेट।',
        sizes: ['2.4', '2.6', '2.8'],
        hasStitchingOption: false,
        replacementPolicy: '7 Days Replacement',
        replacementPolicyHi: '7 दिन की रिप्लेसमेंट'
      }
    ]
  },
  {
    id: 'boutique-7',
    name: 'Sethi Footwear & Shoes',
    nameHi: 'सेठी फुटवियर एंड शूज',
    rating: 4.8,
    deliveryTime: 'Same-Day Delivery',
    deliveryTimeHi: 'उसी दिन डिलीवरी',
    minOrder: 399,
    area: 'Maudaha',
    address: 'Gandhi Ganj, Maudaha',
    addressHi: 'गांधी गंज, मौदहा',
    specialty: 'Premium Leather Jutis, Branded Sport Shoes, Trendy Heels & Daily Slippers',
    specialtyHi: 'प्रीमियम चमड़े की जूती, ब्रांडेड स्पोर्ट्स शूज, ट्रेंडी हील्स और दैनिक चप्पल',
    banner: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?q=80&w=600&auto=format&fit=crop',
    shopType: 'footwear',
    items: [
      {
        id: 'shoe-1-1',
        name: 'Royal Handcrafted Leather Mojari',
        nameHi: 'रॉयल हस्तनिर्मित चमड़े की मोजरी',
        price: 899,
        category: 'footwear',
        image: 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?q=80&w=250&auto=format&fit=crop',
        description: 'Exquisite traditional mojari made with pure tanned leather and embroidery.',
        descriptionHi: 'शुद्ध कमाए गए चमड़े और कढ़ाई के साथ बनाई गई उत्तम पारंपरिक मोजरी।',
        sizes: ['7', '8', '9', '10'],
        hasStitchingOption: false,
        replacementPolicy: '7 Days Replacement',
        replacementPolicyHi: '7 दिन की रिप्लेसमेंट'
      },
      {
        id: 'shoe-1-2',
        name: 'Comfort Walking Sports Sneakers',
        nameHi: 'कम्फर्ट वॉकिंग स्पोर्ट्स स्नीकर्स',
        price: 1499,
        category: 'footwear',
        image: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?q=80&w=250&auto=format&fit=crop',
        description: 'Breathable mesh running and walking shoes, ultra lightweight sole.',
        descriptionHi: 'सांस लेने योग्य जाल वाली रनिंग और वॉकिंग जूते, अल्ट्रा लाइटवेट सोल।',
        sizes: ['7', '8', '9', '10'],
        hasStitchingOption: false,
        replacementPolicy: '7 Days Replacement',
        replacementPolicyHi: '7 दिन की रिप्लेसमेंट'
      },
      {
        id: 'shoe-1-3',
        name: 'Bridal Golden Block Heels',
        nameHi: 'ब्राइडल गोल्डन ब्लॉक हील्स',
        price: 1199,
        category: 'footwear',
        image: 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?q=80&w=250&auto=format&fit=crop',
        description: 'Sparkling golden block heels with cushion pad support, matches wedding wear.',
        descriptionHi: 'कुशन पैड सपोर्ट के साथ चमकदार सुनहरी ब्लॉक हील्स, शादी के परिधानों से मेल खाती हैं।',
        sizes: ['5', '6', '7', '8'],
        hasStitchingOption: false,
        replacementPolicy: '7 Days Replacement',
        replacementPolicyHi: '7 दिन की रिप्लेसमेंट'
      }
    ]
  },
  {
    id: 'boutique-8',
    name: 'Metro Footwear Maudaha',
    nameHi: 'मेट्रो फुटवियर मौदहा',
    rating: 4.7,
    deliveryTime: 'Same-Day Delivery',
    deliveryTimeHi: 'उसी दिन डिलीवरी',
    minOrder: 199,
    area: 'Maudaha',
    address: 'Station Road, Maudaha',
    addressHi: 'स्टेशन रोड, मौदहा',
    specialty: 'Casual Sneakers, Formal Shoes, Stylish Sandals for Ladies',
    specialtyHi: 'कैजुअल स्नीकर्स, फॉर्मल जूते, महिलाओं के लिए स्टाइलिश सैंडल',
    banner: 'https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?q=80&w=600&auto=format&fit=crop',
    shopType: 'footwear',
    items: [
      {
        id: 'shoe-2-1',
        name: 'Executive Men Genuine Leather Formal Shoes',
        nameHi: 'एग्जीक्यूटिव मेन्स असली लेदर फॉर्मल जूते',
        price: 1899,
        category: 'footwear',
        image: 'https://images.unsplash.com/photo-1533867617858-e7b97e060509?q=80&w=250&auto=format&fit=crop',
        description: 'Premium slip-on formal genuine leather dress shoes for corporate look.',
        descriptionHi: 'कॉर्पोरेट लुक के लिए प्रीमियम स्लिप-ऑन फॉर्मल असली लेदर ड्रेस जूते।',
        sizes: ['7', '8', '9', '10'],
        hasStitchingOption: false,
        replacementPolicy: '7 Days Replacement',
        replacementPolicyHi: '7 दिन की रिप्लेसमेंट'
      },
      {
        id: 'shoe-2-2',
        name: 'Strappy Wedge Sandals for Women',
        nameHi: 'महिलाओं के लिए स्ट्रैपी वेज सैंडल',
        price: 899,
        category: 'footwear',
        image: 'https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?q=80&w=250&auto=format&fit=crop',
        description: 'Super comfortable wedges with dynamic strap design, perfect for outfits.',
        descriptionHi: 'डायनेमिक स्ट्रैप डिज़ाइन के साथ सुपर कम्फर्टेबल वेज, परिधानों के लिए एकदम सही।',
        sizes: ['5', '6', '7', '8'],
        hasStitchingOption: false,
        replacementPolicy: '7 Days Replacement',
        replacementPolicyHi: '7 दिन की रिप्लेसमेंट'
      }
    ]
  }
];
